title: weblog
# logo: /assets/img/logo.png
description: thoughts, essays, journal entries, love letters
paginate: 5
paginate_path: "/weblog/page:num/"
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
plugins: 
  - jekyll-paginate
  - jekyll-feed
